version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    image: solar_django_project
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration
      - collectstatic
  migration:
    build: .
    image: solar_django_project
    command: python3 manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
  collectstatic:
    image: solar_django_project
    command: python3 manage.py collectstatic --noinput
    volumes:
      - .:/code